# Generated by Django 5.1.15 on 2026-04-28 20:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookback_days', models.PositiveIntegerField()),
                ('method', models.CharField(default='exp_smoothing', max_length=32)),
                ('alpha', models.DecimalField(decimal_places=3, max_digits=4)),
                ('daily_consumption_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('days_until_stockout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_reorder_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', '-created_at'], name='forecast_fo_product_aaf9b9_idx')],
            },
        ),
    ]
